esphome:
  name: tosot-twinag12-ir-remote
  friendly_name: ESPHome IR AC Control
  min_version: 2025.5.0
  name_add_mac_suffix: false


esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: 'add_your_wifi_ssid_here'
  password: 'add_your_wifi_password_here'

remote_transmitter:
  id: retx
  pin:
    number: D7
        
  carrier_duty_percent: 50%

climate:
  - platform: gree
    name: "Living Room AC"
    model: yac
    icon: "mdi:air-conditioner"
    supports_heat: false